name: build_docker

on:
  push:
    branches:
      - master
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mlops_demo
    steps:
      - name: Setup
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          push: true
      - name: Docker Run Action
        run: docker run --rm --name my_pipeline_container -v /github/workspace/model_outputs/:/home/mlops_demo/_targets/:rw ${{ env.IMAGE_NAME }:${{ github.ref_name }}-${{ github.sha }}}
      - uses: actions/upload-artifact@v3
        with:
          name: model_outputs
          path: /github/workspace/model_outputs/
